//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeVacationScheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation
    {
        public int VacationId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string KindOfVacation { get; set; }
        public string description { get; set; }
    }
}
